/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Price = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductId = IDL.Text;
export const TransactionId = IDL.Nat;
export const Time = IDL.Int;
export const ProductListing = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'timestamp' : Time,
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'commission' : Price,
  'seller' : IDL.Principal,
  'timestamp' : Time,
  'buyer' : IDL.Principal,
  'amount' : Price,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProductListing' : IDL.Func(
      [IDL.Text, IDL.Text, Price, IDL.Text, ExternalBlob],
      [ProductId],
      [],
    ),
  'createTransaction' : IDL.Func(
      [IDL.Principal, IDL.Principal, Price, Price],
      [TransactionId],
      [],
    ),
  'getAllProductListings' : IDL.Func([], [IDL.Vec(ProductListing)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getProductById' : IDL.Func(
      [ProductId],
      [IDL.Opt(ProductListing)],
      ['query'],
    ),
  'getProductListingsSorted' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductListing)],
      ['query'],
    ),
  'getTotalCommission' : IDL.Func([], [Price], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'productListingExists' : IDL.Func([ProductId], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transactionExists' : IDL.Func([TransactionId], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Price = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductId = IDL.Text;
  const TransactionId = IDL.Nat;
  const Time = IDL.Int;
  const ProductListing = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'timestamp' : Time,
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'commission' : Price,
    'seller' : IDL.Principal,
    'timestamp' : Time,
    'buyer' : IDL.Principal,
    'amount' : Price,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProductListing' : IDL.Func(
        [IDL.Text, IDL.Text, Price, IDL.Text, ExternalBlob],
        [ProductId],
        [],
      ),
    'createTransaction' : IDL.Func(
        [IDL.Principal, IDL.Principal, Price, Price],
        [TransactionId],
        [],
      ),
    'getAllProductListings' : IDL.Func(
        [],
        [IDL.Vec(ProductListing)],
        ['query'],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getProductById' : IDL.Func(
        [ProductId],
        [IDL.Opt(ProductListing)],
        ['query'],
      ),
    'getProductListingsSorted' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductListing)],
        ['query'],
      ),
    'getTotalCommission' : IDL.Func([], [Price], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'productListingExists' : IDL.Func([ProductId], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transactionExists' : IDL.Func([TransactionId], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };