/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type Price = bigint;
export type ProductId = string;
export interface ProductListing {
  'id' : ProductId,
  'title' : string,
  'description' : string,
  'seller' : Principal,
  'timestamp' : Time,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type Time = bigint;
export interface Transaction {
  'id' : TransactionId,
  'commission' : Price,
  'seller' : Principal,
  'timestamp' : Time,
  'buyer' : Principal,
  'amount' : Price,
}
export type TransactionId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProductListing' : ActorMethod<
    [string, string, Price, string, ExternalBlob],
    ProductId
  >,
  'createTransaction' : ActorMethod<
    [Principal, Principal, Price, Price],
    TransactionId
  >,
  'getAllProductListings' : ActorMethod<[], Array<ProductListing>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getProductById' : ActorMethod<[ProductId], [] | [ProductListing]>,
  'getProductListingsSorted' : ActorMethod<[string], Array<ProductListing>>,
  'getTotalCommission' : ActorMethod<[], Price>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'productListingExists' : ActorMethod<[ProductId], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transactionExists' : ActorMethod<[TransactionId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];